# Generated by Django 3.1.4 on 2021-06-05 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=60, unique='True', verbose_name='email')),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('firstname', models.CharField(blank=True, max_length=70, null=True)),
                ('lastname', models.CharField(blank=True, max_length=70, null=True)),
                ('phone', models.CharField(max_length=11)),
                ('password', models.CharField(blank=True, max_length=250, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'Applicant',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Contact',
            },
        ),
        migrations.CreateModel(
            name='CreateJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('question_1', models.CharField(blank=True, default='Please tell me about yourself.', editable=False, max_length=250, null=True)),
                ('question_2', models.CharField(blank=True, default='What do you consider as your weakness?', editable=False, max_length=250, null=True)),
                ('question_3', models.CharField(blank=True, default='What are your goals?', editable=False, max_length=250, null=True)),
                ('question_4', models.CharField(blank=True, default='What are your actions if employees disagreed with your decision?', editable=False, max_length=250, null=True)),
                ('question_5', models.CharField(blank=True, default='What can you do for us that other candidates cannot?', editable=False, max_length=250, null=True)),
                ('question_6', models.CharField(blank=True, default='Describe a situation where results went against expectations. How did you adapt to this change?', editable=False, max_length=250, null=True)),
                ('question_7', models.CharField(blank=True, default='Can you discuss a time where you had to manage your team through a difficult situation?', editable=False, max_length=250, null=True)),
                ('question_8', models.CharField(blank=True, default='How do you prioritize your tasks when you have multiple deadlines to meet?', editable=False, max_length=250, null=True)),
                ('question_9', models.CharField(blank=True, default='What is the most significant problem you solved in the workplace?', editable=False, max_length=250, null=True)),
                ('question_10', models.CharField(blank=True, default='How do you explain new topics to coworkers unfamiliar with them?', editable=False, max_length=250, null=True)),
                ('question_11', models.CharField(blank=True, max_length=250, null=True)),
                ('question_12', models.CharField(blank=True, max_length=250, null=True)),
                ('question_13', models.CharField(blank=True, max_length=250, null=True)),
                ('question_14', models.CharField(blank=True, max_length=250, null=True)),
                ('question_15', models.CharField(blank=True, max_length=250, null=True)),
                ('question_16', models.CharField(blank=True, max_length=250, null=True)),
                ('question_17', models.CharField(blank=True, max_length=250, null=True)),
                ('question_18', models.CharField(blank=True, max_length=250, null=True)),
                ('question_19', models.CharField(blank=True, max_length=250, null=True)),
                ('question_20', models.CharField(blank=True, max_length=250, null=True)),
                ('requirement1', models.CharField(blank=True, max_length=250, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Job_Offerings',
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.createjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SavedJobs',
            },
        ),
        migrations.CreateModel(
            name='AppliedJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_1', models.TextField(null=True)),
                ('response_2', models.TextField(null=True)),
                ('response_3', models.TextField(null=True)),
                ('response_4', models.TextField(null=True)),
                ('response_5', models.TextField(null=True)),
                ('response_6', models.TextField(null=True)),
                ('response_7', models.TextField(null=True)),
                ('response_8', models.TextField(null=True)),
                ('response_9', models.TextField(null=True)),
                ('response_10', models.TextField(null=True)),
                ('response_11', models.TextField(null=True)),
                ('response_12', models.TextField(null=True)),
                ('response_13', models.TextField(null=True)),
                ('response_14', models.TextField(null=True)),
                ('response_15', models.TextField(null=True)),
                ('response_16', models.TextField(null=True)),
                ('response_17', models.TextField(null=True)),
                ('response_18', models.TextField(null=True)),
                ('response_19', models.TextField(null=True)),
                ('response_20', models.TextField(null=True)),
                ('requirement_1', models.CharField(blank=True, max_length=250, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CreateJob', to='user.createjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Applicant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AppliedJob',
            },
        ),
    ]
