# Generated by Django 3.1.4 on 2021-06-05 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='createjob',
            table='JobOfferings',
        ),
    ]
