# Generated by Django 2.1.15 on 2021-06-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createjob',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
