# Generated by Django 2.1.15 on 2021-06-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createjob',
            name='requirement1',
        ),
        migrations.AddField(
            model_name='createjob',
            name='timer1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='timer10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='timer2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='timer3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='timer4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='timer5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='timer6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='timer7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='timer8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='timer9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='weight1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='weight10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='weight2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='weight3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='weight4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='weight5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='weight6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='weight7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='weight8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='createjob',
            name='weight9',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
