# Generated by Django 3.1.4 on 2021-06-05 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210605_1833'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='savedjob',
            table='SavedJob',
        ),
    ]
